# Generated by Django 2.0.7 on 2018-07-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节名')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='章节更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='FictionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='小说类型')),
            ],
        ),
        migrations.CreateModel(
            name='Fition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='小说名')),
                ('intro', models.TextField(max_length=200, verbose_name='作品简介')),
                ('cover', models.CharField(max_length=300, verbose_name='封面图片')),
                ('put_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('click', models.PositiveIntegerField(default=0, verbose_name='作品点击数')),
                ('author', models.CharField(max_length=20, unique=True, verbose_name='作者名')),
                ('fictionType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qw_app.FictionType')),
            ],
        ),
    ]
