# Generated by Django 2.0.7 on 2018-07-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='作者名')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='章节名')),
                ('content', models.TextField(verbose_name='小说内容')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='章节更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='FictionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='小说类型')),
            ],
        ),
        migrations.CreateModel(
            name='Fition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='小说名')),
                ('intro', models.CharField(max_length=200, verbose_name='作品简介')),
                ('cover', models.CharField(max_length=300, verbose_name='封面图片')),
                ('put_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='小说更新时间')),
                ('click', models.PositiveIntegerField(default=0, verbose_name='作品点击数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qw_app.Author')),
                ('fictionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qw_app.FictionType')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='用户账号')),
                ('passwd', models.CharField(max_length=20, verbose_name='用户密码')),
                ('email', models.CharField(max_length=20, unique=True, verbose_name='用户邮箱')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='电话')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=1)),
                ('head_img', models.ImageField(upload_to='photos', verbose_name='用户头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
            ],
        ),
        migrations.AddField(
            model_name='fition',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qw_app.Users'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='fiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qw_app.Fition'),
        ),
    ]
