# Generated by Django 2.0.7 on 2018-07-20 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qw_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fition',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='fiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qw_app.Fition'),
        ),
    ]
