# Generated by Django 2.0.7 on 2018-07-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qw_app', '0002_remove_fition_updata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fition',
            name='author',
            field=models.CharField(max_length=20, unique=True, verbose_name='作者名'),
        ),
        migrations.AlterField(
            model_name='fition',
            name='fictionType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qw_app.FictionType'),
        ),
        migrations.AlterField(
            model_name='fition',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qw_app.Users'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
