# Generated by Django 2.0.7 on 2018-07-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qw_app', '0003_auto_20180718_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fition',
            name='intro',
            field=models.TextField(max_length=200, verbose_name='作品简介'),
        ),
    ]
